# config/meta.yml

meta_product_name: "Martin Kevin Gapie's Portfolio"
meta_title: "Portfolio de Martin Kevin Gapie"
meta_description: "Une expertise unique pour votre site web"
meta_image: "meta_image.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
