# config/meta.yml

meta_product_name: "Martin Kevin Gapie's Portfolio"
meta_title: "Martin Kevin Gapie's Portfolio"
meta_description: "Computer scientiest and web developer"
meta_image: "meta_image.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
